- name: Deploy private image from nexus
  hosts: client
  vars:
    nexus_registry: "20.163.228.142:8085"
    image_name: "nexus-pvt:latest"
    container_name: "myapp"
    nexus_username: "admin"
    nexus_password: "admin"
  tasks:
  - name: login to nexus
    docker_login:
      registry_url: "{{ nexus_registry }}"
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"

  - name: pull image from nexus
    docker_image:
      name: "{{ nexus_registry }}/{{ image_name }}"
      source: pull

  - name: stop running container
    docker_container:
      name: "{{ container_name }}"
      state: stopped

  - name: start new container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ nexus_registry }}/{{ image_name }}"
      state: started