---
- name: Deploy Private Image from Nexus Repository
  hosts: all
  vars:
    image_name: "my_private_image"
    nexus_url: "http://20.163.228.142:8081"
    nexus_repo: "nexus-pvt"
    container_name: "my_container"
    nexus_password : "admin"

  tasks:
  - name: Login to Nexus
    command: >
      docker login {{ nexus_url }} -u admin -p {{ nexus_password }}

  - name: Pull Private Image
    command: >
      docker pull {{ nexus_url }}/{{ nexus_repo }}/{{ image_name }}

  - name: Run Private Image in a container
    command: >
      docker run -d --name {{ container_name }}
      {{ nexus_url }}/{{ nexus_repo }}/{{ image_name }}